name: NodeJS build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Node ${{ matrix.node-version }} build
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Packages
      run: npm ci

    - name: Build 
      run: npm run build
    
  

  cypress-test:
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, edge, firefox]
    
    name: Cypress Test on  ${{ matrix.browser }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run on  ${{ matrix.browser }} 
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          build: npm run build
          start: npm run serve:test
          browser: ${{ matrix.browser }}