name: NodeJS build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:


  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    name: Node ${{ matrix.node-version }} build

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

 
    - run: npm ci
    - run: npm run build
    

  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, edge, firefox]

    name: Cypress Test on  ${{ matrix.node }} build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build First
        run: |
          npm ci
          npm run build
          npm serve

      - name: Cypress run on ${{ matrix.browser }}
        run: npm run cy:run -- --browser ${{ matrix.browser }}

        
        
        # uses: cypress-io/github-action@v4
        # with:
        #   start: npm serve
        #   # quote the url to be safe against YML parsing surprises
        #   wait-on: 'http://localhost:8080'
        #   browser: ${{ matrix.browser }}

  # publish:
  #   runs-on: ubuntu-latest

  #   name: publish to npm
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: '14.x'
  #       registry-url: 'https://registry.npmjs.org'
  #   - run: npm ci
  #   - run: npm publish
  #     env:
  #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  #   - uses: actions/setup-node@v3
  #     with:
  #       registry-url: 'https://npm.pkg.github.com'
  #   - run: npm publish
  #     env:
  #       NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

